name: tsdm_converter
description: "Converter among different dataframes for tsdm"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  flutter: ">=3.25.0 <4.0.0"
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  # Blocked by flutter
  collection: any
  dart_mappable: ^4.6.1
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  gitsumu: ^0.7.0
  html: ^0.15.6
  super_clipboard: ^0.9.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  dart_mappable_builder: ^4.3.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pyramid_lint: ^2.3.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
